services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/home/backups
    command: -p 5433
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/myst
    ports:
      - "3000:3000"
    depends_on:
      - db